Register, login and logout user both on server and cli
PostScripton/passwords-manager-gophkeeper pull request #1
Opened 2023-02-05 18:40 UTC by PostScripton

2023-02-09 16:47 UTC, kilchik requested changes

2023-02-09 16:47 UTC, kilchik commented on cmd/cli/commands/login.go
> +		login, password := args[0], args[1]
Не увидел проверки на число аргументов в слайсе

2023-02-09 16:47 UTC, kilchik commented on cmd/server/main.go
> +	repo := repository.NewRepository(factory)
А почему сервер использует in-memory хранилище? Это временно? У нас же все пароли пропадут при рестарте сервера

2023-02-09 16:47 UTC, kilchik commented on internal/repository/memory/settings.go
> +package memory
А SettingsRepository - для хранения паролей? Неочевидное название

2023-02-09 18:06 UTC, PostScripton commented on cmd/server/main.go
> +	repo := repository.NewRepository(factory)
Конечно это всё временно 🤣, я ещё не сделал постгрес. Но благодаря абстрактной фабрике я легко смогу заменить это хранилище на другое `factory := postgres.NewFactory()`

2023-02-09 18:08 UTC, PostScripton commented on cmd/cli/commands/login.go
> +		login, password := args[0], args[1]
Там у меня выше стоит в найстройках команды кобры - минимальное кол-во аргументов. Если бы было больше минимального, то пришло бы проверять, что я и сделал в части с secrets, которую ещё не выгрузил

2023-02-09 18:11 UTC, PostScripton commented on internal/repository/memory/settings.go
> +package memory
Это для хранения вообще любых значений в виде `ключ -> значение`. Я тут храню jwt, encAesSecret, encPrivateKey. В теории тут может храниться вообще любые вспомогательные данные, которые должны сохраняться (иметь стейт), т.к. кобра работает в рамках одной команды.

2023-02-11 16:13 UTC, merged

2023-02-16 16:25 UTC, kilchik commented on cmd/cli/main.go
> +	cfg := config.NewConfig("./config")
Нужен graceful shutdown по сигналу от ОС - базу корректно закрывать, "красивое" сообщение пользователю выводить

2023-02-16 18:08 UTC, PostScripton commented on cmd/cli/main.go
> +	cfg := config.NewConfig("./config")
Ой, да, забыл сделать. Реализую и для клиента, и для сервера