Storing credentials secrets
PostScripton/passwords-manager-gophkeeper pull request #2
Opened 2023-02-11 20:32 UTC by PostScripton

2023-02-17 18:54 UTC, kilchik requested changes

2023-02-17 18:54 UTC, kilchik commented on cmd/cli/commands/add_creds.go
> +package commands
Бинарники не стоит в репозиторий добавлять

2023-02-17 18:54 UTC, kilchik commented on cmd/cli/commands/add_creds.go
> +import (
Я бы предложил положить commands в /internal/client/commands. В cmd обычно только входная точка в приложение

2023-02-17 18:54 UTC, kilchik commented on internal/server/creds_handlers.go
> +		log.Error().Err(err).Msg("Getting credentials list for the user")
В таких логах всегда лучше дать побольше деталей (в данном случае userID хорошо бы залогировать)

2023-02-17 18:54 UTC, kilchik commented on cmd/cli/commands/add_creds.go
> +		uploadCreds(cmd)
Получается, на каждое добавление пароля у нас все данные будут отправляться на сервер? Не очень красиво конечно, лучше бы отправлять только то, что обновилось

2023-02-17 18:54 UTC, kilchik commented on internal/client/creds_client.go
> +		grpc.WithTransportCredentials(insecure.NewCredentials()),
Здесь хотелось бы видеть SSL - все-таки пароли по сети передаем

2023-02-19 16:38 UTC, PostScripton commented on cmd/cli/commands/add_creds.go
> +package commands
Done

2023-02-19 16:38 UTC, PostScripton commented on internal/client/creds_client.go
> +		grpc.WithTransportCredentials(insecure.NewCredentials()),
Done

2023-02-19 16:40 UTC, PostScripton commented on cmd/cli/commands/add_creds.go
> +import (
Done. Поместил в `/internal/cli/commands`

2023-02-19 16:56 UTC, PostScripton commented on internal/server/creds_handlers.go
> +		log.Error().Err(err).Msg("Getting credentials list for the user")
Done. Добавил во все логи побольше инфы, где это возможно.

2023-02-19 16:58 UTC, PostScripton commented on cmd/cli/commands/add_creds.go
> +		uploadCreds(cmd)
У меня такая реализация получилась, она не идеальна, но она работает. На б**О**льшее времени не хватило :(

2023-02-19 17:02 UTC, PostScripton commented
https://github.com/PostScripton/passwords-manager-gophkeeper/pull/1#pullrequestreview-1301822972
По поводу комментария о graceful shutdown.

Оказывается он у меня уже был реализован на сервере, а в CLI он не нужен, т.к. я использую кобру, там "приложение" и так живёт только во время выполнения одной команды, т.к. там некогда тупо будет получать системные сигналы.
Если бы я реализовывал CLI, как у редиса, когда я захожу в интерактивный shell, то да, там нужно было бы реализовывать его.

2023-02-25 19:06 UTC, PostScripton reviewed
@kilchik, надеюсь это последние правки, постарался написать тесты на сервисы и репозиторий, очень много времени на них ушло :D

2023-02-27 18:11 UTC, kilchik approved these changes

2023-02-27 19:18 UTC, merged